export const dates = [
    'Early January',
    'Mid January',
    'Early February',
    'Mid February',
    'Early March',
    'Mid March',
    'Early April',
    'Mid April',
    'Early May',
    'Mid  May',
    'Early June',
    'Mid June',
    'Early July',
    'Mid July',
    'Early August',
    'Mid August',
    'Early September',
    'Mid September',
    'Early October',
    'Mid October',
    'Early Novemeber',
    'Mid Novemeber',
    'Early December',
    'Mid December'
]